
spring:
  datasource:
    url: jdbc:h2:mem:nodemo
    username: admin
    password:

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: volume
      password: volume