
spring:
  datasource:
    url: jdbc:sqlserver://207-9;databaseName=ddos;integratedSecurity=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver



  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect:org:hibernate: dialect.SQLServer2012Dialect
  security:
    user:
      name: volume
      password: volume